#!/bin/bash

DISCOVERY_PASSWORD="my-password"
DISCOVERY_USERNAME="my-username"
EUREKA_SERVER_PORT=8001
EUREKA_HOSTNAME="localhost"

IMAGE_NAME="discovery_serv"

docker run -d -p ${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT} \
  -e DISCOVERY_PASSWORD=${DISCOVERY_PASSWORD} \
  -e DISCOVERY_USERNAME=${DISCOVERY_USERNAME} \
  -e SERVER_PORT=${EUREKA_SERVER_PORT} \
  -e EUREKA_HOSTNAME=${EUREKA_HOSTNAME} \
  ${IMAGE_NAME}