spring:
  application:
    name: BsDiscoveryServer
server:
  port: ${EUREKA_SERVER_PORT:8008}
eureka:
  server:
    eviction-interval-timer-in-ms: 20000
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    lease-expiration-duration-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.config: DEBUG